def usage():
    print("Waffle's Compiler!")
    print("")
    print("USAGE: ")
    print("    waffle [OPTIONS] [SUBCOMMAND]")
    print("")
    print("OPTIONS:")
    print("    -h, --help             Prints help information")
    print("")
    print("SUBCOMMAND:")
    print("    [Input File]")
    print("")
    print("OPTIONAL SUBCOMMANDS:")
    print("    -o, --output          Specify the output filename")
    print("")
    print("Example Usage: waffle examples/hello.bf -o hello")
