def usage():
    print("")
    print("Waffle's Compiler!")
    print("")
    print("USAGE: ")
    print("    waffle [OPTIONS] [SUBCOMMAND]")
    print("")
    print("OPTIONS:")
    print("    -h, --help                     Prints help information")
    print("    -v, --version                  Prints the compiler version")
    print("")
    print("SUBCOMMAND:")
    print("    -f, --file [Input File]        Specify the input file")
    print("")
    print("OPTIONAL SUBCOMMANDS:")
    print("    -o, --output                   Specify the output filename")
    print("")
    print("Example Usage: waffle examples/hello.bf -o hello")
